name: my_server
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  alfred: ^1.1.1
  hive: ^2.2.3
  path_provider: ^2.1.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
